## NumPy (Numerical Python)

NumPy, bilimsel hesaplamalar ve cebir işlemleri için geliştirilmiş temel Python kütüphanesidir. Makine Öğrenmesi, Derin Öğrenme ve Görüntü İşleme konularında sıkça kullanılmaktadır.

**Site:** [https://numpy.org/](https://numpy.org/)

**Quickstart Tutorial:** [https://numpy.org/devdocs/user/quickstart.html](https://numpy.org/devdocs/user/quickstart.html)

**Stanford CS231n:** [http://cs231n.github.io/python-numpy-tutorial/#python-functions](http://cs231n.github.io/python-numpy-tutorial/#python-functions)

**!!!:** http://kisi.deu.edu.tr//levent.senyay/bilgisayarprogramlama/5_4%20python%20Numpy%20K%c3%bct%c3%bcphanesi.pdf **!!!**

### Kurulum

In [1]:
# !conda install numpy
# !pip install numpy

In [2]:
import numpy as np

In [3]:
print('NumPy Version:', np.__version__)

NumPy Version: 1.18.1


In [4]:
np

<module 'numpy' from 'C:\\Users\\METIN.USLU\\.conda\\envs\\lcw_env\\lib\\site-packages\\numpy\\__init__.py'>

In [5]:
# Function & Attiribute
# dir(np)

### Scalar, Vector, Matrix, Tensor

![image info](./Garbage/Type1_2.png)

**Source:** https://hadrienj.github.io/posts/Deep-Learning-Book-Series-2.1-Scalars-Vectors-Matrices-and-Tensors/

![image info](./Garbage/Type1_3.jpg)

**Source:** [https://pbs.twimg.com/media/D2xTDMJWwAADHQt.jpg](https://pbs.twimg.com/media/D2xTDMJWwAADHQt.jpg)

**<center>1D Array, 2D Array and 3D Array</center>**

![image info](./Garbage/Type2_1.png)

**Source:** https://fgnt.github.io/python_crashkurs_doc/include/numpy.html

In [6]:
x = np.array([2, 3, 5, 7, 11])

print(x)

print('Type:', type(x), 'Shape:', x.shape, 'Dimension(Rank):', x.ndim, 'DType:', x.dtype)

[ 2  3  5  7 11]
Type: <class 'numpy.ndarray'> Shape: (5,) Dimension(Rank): 1 DType: int32


In [7]:
print(x[0], x[1], x[2], x[3], x[4])

2 3 5 7 11


In [8]:
l1 = [1, 2, 3, 4, 5]

x = np.array(l1)

print(x)

print('Type:', type(x), 'Shape:', x.shape, 'Dimension(Rank):', x.ndim, 'DType:', x.dtype)

[1 2 3 4 5]
Type: <class 'numpy.ndarray'> Shape: (5,) Dimension(Rank): 1 DType: int32


In [9]:
print(x[0], x[1], x[2], x[3], x[4])

1 2 3 4 5


In [10]:
x[0] = 10
print(x)

[10  2  3  4  5]


In [11]:
l1 = [ [2, 4, 8], [3, 9, 27], [5, 25, 125] ]

y = np.array(l1)

# y = np.array([[2,4,6], [3,6,9], [4, 8, 12]])

print(y)

[[  2   4   8]
 [  3   9  27]
 [  5  25 125]]


In [12]:
print('Type:', type(y), 'Shape:', y.shape, 'Dimension(Rank):', y.ndim, 'DType:', y.dtype)

Type: <class 'numpy.ndarray'> Shape: (3, 3) Dimension(Rank): 2 DType: int32


In [13]:
print(y[0,0], y[1,0], y[2,0])
print(y[0,1], y[1,1], y[2,1])
print(y[0,2], y[1,2], y[2,2])

2 3 5
4 9 25
8 27 125


In [14]:
l2 = [[ [2, 4, 6], [3, 6, 9], [4, 8, 12] ]]

z = np.array(l2)

# y = np.array([[2,4,6], [3,6,9], [4, 8, 12]])

print(z)

[[[ 2  4  6]
  [ 3  6  9]
  [ 4  8 12]]]


In [15]:
print('Type:', type(z), 'Shape:', z.shape, 'Dimension(Rank):', z.ndim, 'DType:', z.dtype)

Type: <class 'numpy.ndarray'> Shape: (1, 3, 3) Dimension(Rank): 3 DType: int32


### Dizi Oluşturma

#### np.arange()

In [16]:
a1 = np.arange(0, 10)
# a1 = np.arange(0, 10, 1)

print(a1)

print('Type:', type(a1), 'Shape:', a1.shape, 'Dimension(Rank):', a1.ndim, 'DType:', a1.dtype)

[0 1 2 3 4 5 6 7 8 9]
Type: <class 'numpy.ndarray'> Shape: (10,) Dimension(Rank): 1 DType: int32


In [17]:
a2 = np.arange(0, 13, 3)

print(a2)

[ 0  3  6  9 12]


#### np.linspace()

In [18]:
a3 = np.linspace(0, 10, 6)

print(a3)

[ 0.  2.  4.  6.  8. 10.]


#### np.zeros()

In [19]:
b1 = np.zeros(3)
b1

array([0., 0., 0.])

In [20]:
b2 = np.zeros((4, 4))
b2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### np.ones()

In [21]:
c1 = np.ones(3)
c1

array([1., 1., 1.])

In [22]:
c2 = np.ones((3, 3))
c2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### np.full()

In [23]:
d = np.full((3, 3), 5)
d

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

#### np.eye()

In [24]:
e = np.eye((5))
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### np.empyt()

In [25]:
f = np.empty((2, 4))
print(f)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 6.67976753e-321 3.11524430e-307 8.45559302e-307]]


In [26]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of uninitialized (arbitrary) data of the given shape, dtype, and
        order.  Object arrays will be initialized to None.
    
    See Also
    --------
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting values to one.
    zeros : Return a new array 

#### np.random.random

In [27]:
# Random Numbers
g1 = np.random.random((4))

print(g1)

print('Type:', type(g1), 'Shape:', g1.shape, 'Dimension(Rank):', g1.ndim, 'DType:', g1.dtype)

[0.71016634 0.74062063 0.70191233 0.43114153]
Type: <class 'numpy.ndarray'> Shape: (4,) Dimension(Rank): 1 DType: float64


In [28]:
g2 = np.random.random((4, 4))

print(g2)

print('Type:', type(g2), 'Shape:', g2.shape, 'Dimension(Rank):', g2.ndim, 'DType:', g2.dtype)

[[0.20216087 0.79036176 0.92614036 0.15243672]
 [0.95936145 0.23783773 0.67840747 0.98905463]
 [0.98265465 0.79939884 0.26734143 0.89779815]
 [0.54452981 0.81427813 0.01784385 0.940403  ]]
Type: <class 'numpy.ndarray'> Shape: (4, 4) Dimension(Rank): 2 DType: float64


#### np.random.rand

In [29]:
# Standart Uniform Distribution (Standart Tek Düze Dağılım)

h1 = np.random.rand(4)
h1

print('Type:', type(h1), 'Shape:', h1.shape, 'Dimension(Rank):', h1.ndim, 'DType:', h1.dtype)

Type: <class 'numpy.ndarray'> Shape: (4,) Dimension(Rank): 1 DType: float64


In [30]:
h2 = np.random.rand(3, 3)
h2

print('Type:', type(h2), 'Shape:', h2.shape, 'Dimension(Rank):', h2.ndim, 'DType:', h2.dtype)

Type: <class 'numpy.ndarray'> Shape: (3, 3) Dimension(Rank): 2 DType: float64


#### np.random.randn

In [31]:
# Standart Normal Distribution (Standart Normal Dağılım, 0, 1)

j1 = np.random.randn(2)
j1

array([ 1.53031834, -0.53099463])

In [32]:
j2 = np.random.randn(3, 3)
j2

array([[-1.26157875, -0.39854935,  0.50636744],
       [ 0.89690896,  0.48300637, -1.5896129 ],
       [ 0.68622826,  0.73547504,  0.59955748]])

#### np.random.randint

In [33]:
# Integer

k1 = np.random.randint(1, 100)
k1

50

In [34]:
k2 = np.random.randint(1, 50, 10)
k2

array([17, 27,  7,  5, 24, 22, 41, 46, 38, 49])

### Numpy Methods

In [35]:
d1 = np.arange(12)
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
d2 = np.random.randint(0, 25, 12)
d2

array([21, 23, 10, 23, 24, 18,  3, 11, 21, 23, 11, 23])

In [37]:
d1.shape

(12,)

In [38]:
d1.reshape(6, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [39]:
d1.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [40]:
d1.reshape(2,6).shape

(2, 6)

In [41]:
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
d1.resize(2, 6)
d1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

**Not a Number:** np.nan() **&** **Infinite:** np.inf()

In [43]:
e = np.array([ [0, np.nan], [1, np.inf] ])
e

array([[ 0., nan],
       [ 1., inf]])

**Transpose**

In [44]:
d1.T

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [45]:
d1.shape

(2, 6)

In [46]:
d1.resize(6, 2)
d1

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [47]:
d1.shape

(6, 2)

In [48]:
d1 = d1.ravel()
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
d1.shape

(12,)

In [50]:
arr1 = d1.copy()
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
d3 = d1.reshape(3, 4)
d3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
print('Array:', d2)
print('Type:', type(d2))
print('Shape:', d2.shape)
print('Size:', d2.size)
print('NDim:', d2.ndim)
print('DType:', d2.dtype)

Array: [21 23 10 23 24 18  3 11 21 23 11 23]
Type: <class 'numpy.ndarray'>
Shape: (12,)
Size: 12
NDim: 1
DType: int32


### Selection & Slicing

In [53]:
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
d1[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [55]:
d3[:,:]
# d3[:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Rows Base

In [56]:
d3[0,:]
# d3[0]

array([0, 1, 2, 3])

In [57]:
d3[1,:]
d3[1]

array([4, 5, 6, 7])

In [58]:
d3[2,:]
d3[2]

array([ 8,  9, 10, 11])

#### Columns Base

In [59]:
d3[:,0]

array([0, 4, 8])

In [60]:
d3[:,1]

array([1, 5, 9])

In [61]:
d3[:,2]

array([ 2,  6, 10])

In [62]:
d3[:,3]

array([ 3,  7, 11])

In [63]:
d3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
d4 = d3.ravel()[0:9].reshape(3,3)
d4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
# Spesific

In [66]:
print(d4[0,0], d4[1,1], d4[2,2])

0 4 8


In [67]:
d4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
d4[1,2]

5

In [69]:
d4[1][2]

5

In [70]:
d4[1:3, 1:3]

array([[4, 5],
       [7, 8]])

In [71]:
d4[2][2] = 80
d4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7, 80]])

 ### Add Two Array

In [72]:
a1 = np.array([ [1,2], [3,4] ])

a2 = np.array([ [5,6], [7,8] ])

In [73]:
a1

array([[1, 2],
       [3, 4]])

In [74]:
a2

array([[5, 6],
       [7, 8]])

In [75]:
# Vertical
np.vstack((a1, a2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [76]:
np.concatenate([a1, a2], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [77]:
#Horizontal
np.hstack((a1, a2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [78]:
np.concatenate([a1, a2], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Filtreleme

In [79]:
d2

array([21, 23, 10, 23, 24, 18,  3, 11, 21, 23, 11, 23])

In [80]:
d2 > 13

array([ True,  True, False,  True,  True,  True, False, False,  True,
        True, False,  True])

In [81]:
d2 [d2 > 13]

array([21, 23, 23, 24, 18, 21, 23, 23])

In [82]:
d2 [d2 > 13] = 130
d2

array([130, 130,  10, 130, 130, 130,   3,  11, 130, 130,  11, 130])

### Aritmetik Operatörler

In [83]:
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7, 80,  9, 10, 11])

In [84]:
d2

array([130, 130,  10, 130, 130, 130,   3,  11, 130, 130,  11, 130])

In [85]:
d1 + d2

array([130, 131,  12, 133, 134, 135,   9,  18, 210, 139,  21, 141])

In [86]:
np.add(d1, d2)

array([130, 131,  12, 133, 134, 135,   9,  18, 210, 139,  21, 141])

In [87]:
d1 - d2

array([-130, -129,   -8, -127, -126, -125,    3,   -4,  -50, -121,   -1,
       -119])

In [88]:
np.subtract(d1,d2)

array([-130, -129,   -8, -127, -126, -125,    3,   -4,  -50, -121,   -1,
       -119])

In [89]:
d1 * d2

array([    0,   130,    20,   390,   520,   650,    18,    77, 10400,
        1170,   110,  1430])

In [90]:
np.multiply(d1,d2)

array([    0,   130,    20,   390,   520,   650,    18,    77, 10400,
        1170,   110,  1430])

In [91]:
d1 / d2

array([0.        , 0.00769231, 0.2       , 0.02307692, 0.03076923,
       0.03846154, 2.        , 0.63636364, 0.61538462, 0.06923077,
       0.90909091, 0.08461538])

In [92]:
np.divide(d1, d2)

array([0.        , 0.00769231, 0.2       , 0.02307692, 0.03076923,
       0.03846154, 2.        , 0.63636364, 0.61538462, 0.06923077,
       0.90909091, 0.08461538])

In [93]:
d1 * 5

array([  0,   5,  10,  15,  20,  25,  30,  35, 400,  45,  50,  55])

In [94]:
np.multiply(d1, 5)

array([  0,   5,  10,  15,  20,  25,  30,  35, 400,  45,  50,  55])

In [95]:
np.dot(d1,5)

array([  0,   5,  10,  15,  20,  25,  30,  35, 400,  45,  50,  55])

In [96]:
# Inner Product
d1.dot(d2)

14915

In [97]:
# Inner Product
np.dot(d1,d2)

14915

In [98]:
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7, 80,  9, 10, 11])

In [99]:
d1 ** 2

array([   0,    1,    4,    9,   16,   25,   36,   49, 6400,   81,  100,
        121], dtype=int32)

In [100]:
np.square(d1)

array([   0,    1,    4,    9,   16,   25,   36,   49, 6400,   81,  100,
        121], dtype=int32)

In [101]:
pow(d1,2)

array([   0,    1,    4,    9,   16,   25,   36,   49, 6400,   81,  100,
        121], dtype=int32)

In [102]:
d1 ** 0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 8.94427191, 3.        ,
       3.16227766, 3.31662479])

In [103]:
np.sqrt(d1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 8.94427191, 3.        ,
       3.16227766, 3.31662479])

In [104]:
np.sin(d1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 , -0.99388865,  0.41211849,
       -0.54402111, -0.99999021])

In [105]:
np.cos(d1)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.11038724, -0.91113026,
       -0.83907153,  0.0044257 ])

In [106]:
np.sqrt(d1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 8.94427191, 3.        ,
       3.16227766, 3.31662479])

In [107]:
np.square(d1)

array([   0,    1,    4,    9,   16,   25,   36,   49, 6400,   81,  100,
        121], dtype=int32)

In [108]:
np.exp(d1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       5.54062238e+34, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04])

In [109]:
np.log(d1)

C:\Users\METIN.USLU\.conda\envs\lcw_env\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 4.38202663, 2.19722458,
       2.30258509, 2.39789527])

**Min: np.min()**

In [110]:
d3.min()

0

In [111]:
d3.argmin()

0

In [112]:
np.min(d3, axis=0) #Rows Base

array([0, 1, 2, 3])

In [113]:
np.min(d3, axis=1) #Columns Base

array([0, 4, 9])

**Max: np.max()**

In [114]:
d3.max()

80

In [115]:
d3.argmax()

8

In [116]:
np.max(d3, axis=0) #Rows Base

array([80,  9, 10, 11])

In [117]:
np.max(d3, axis=1) #Columns Base

array([ 3,  7, 80])

**Sum: np.sum()**

In [118]:
d3.sum()

138

In [119]:
np.sum(d3)

138

In [120]:
np.sum(d3, axis=0) #Columns Based

array([84, 15, 18, 21])

In [121]:
np.sum(d3, axis=1) #Row Based

array([  6,  22, 110])

**Mean: np.mean()**

In [122]:
d1.mean()

11.5

In [123]:
d3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [80,  9, 10, 11]])

In [124]:
np.mean(d3, axis=0) #Columns Based

array([28.,  5.,  6.,  7.])

In [125]:
np.mean(d3, axis=1) #Rows Based

array([ 1.5,  5.5, 27.5])

In [126]:
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7, 80,  9, 10, 11])

In [127]:
d1 - d1.mean()

array([-11.5, -10.5,  -9.5,  -8.5,  -7.5,  -6.5,  -5.5,  -4.5,  68.5,
        -2.5,  -1.5,  -0.5])

**Median: np.median()**

In [128]:
np.median(d1)

5.5

**Variance: np.var()**

In [129]:
np.var(d1)

437.9166666666667

**Standart Deviation: np.std()**

In [130]:
np.std(d1)

20.92645853140628

**Unique: np.unique()**

In [131]:
d4 = np.array([ 1, 2, 2, 1, 1, 5, 4, 5, 6, 3, 6, 4, 5])
print(d4)

u, c = np.unique(d4, return_counts=True)

print("Unique Elemanlar")
print(u)

print("Unique Elemanların Adetleri")
print(c)

[1 2 2 1 1 5 4 5 6 3 6 4 5]
Unique Elemanlar
[1 2 3 4 5 6]
Unique Elemanların Adetleri
[3 2 1 2 3 2]


### Image

In [132]:
# pip install Pillow or conda install Pillow
# https://www.pluralsight.com/guides/importing-image-data-into-numpy-arrays
# scipy, matplotlib, opencv, keras

from PIL import Image
import numpy as np

# load the image
file = './Garbage/IMG-3577.jpeg'
image1 = Image.open(file)

print('Image Mode:', image1.mode)
print('Image Size:', image1.size)

Image Mode: RGB
Image Size: (563, 697)


In [133]:
# from PIL import Image
# from IPython.display import display

# file = './Garbage/IMG-3577.jpeg'
# display(Image.open(file))


# from IPython.display import Image
# Image(filename = file)

In [134]:
# convert image to numpy array
data1 = np.asarray(image1)

print('Type:', type(data1))
print('Shape:', data1.shape)
print('Dimension(Rank):', data1.ndim)
print('DType:', data1.dtype)

Type: <class 'numpy.ndarray'>
Shape: (697, 563, 3)
Dimension(Rank): 3
DType: uint8


In [135]:
print(data1)

[[[ 65  67  80]
  [ 53  55  68]
  [ 51  53  66]
  ...
  [ 44  42  63]
  [ 47  45  66]
  [ 58  56  77]]

 [[ 62  64  77]
  [ 51  53  66]
  [ 49  51  64]
  ...
  [ 43  44  62]
  [ 45  46  64]
  [ 55  56  74]]

 [[ 60  62  75]
  [ 50  52  65]
  [ 49  51  64]
  ...
  [ 44  46  61]
  [ 45  47  62]
  [ 54  56  71]]

 ...

 [[125 113 113]
  [102  92  91]
  [101  91  92]
  ...
  [117 118 122]
  [101 102 106]
  [ 89  90  94]]

 [[124 112 112]
  [104  92  92]
  [101  91  90]
  ...
  [119 120 124]
  [114 115 119]
  [109 110 114]]

 [[115 103 103]
  [102  90  90]
  [106  96  95]
  ...
  [ 54  54  56]
  [107 107 109]
  [126 126 128]]]


In [136]:
# Create Pillow Image

image2 = Image.fromarray(data1)

print('Type:', type(image2))

Type: <class 'PIL.Image.Image'>


In [137]:
# Summarize Image Details

print('Image Mode:', image2.mode)
print('Image Size:', image2.size)

Image Mode: RGB
Image Size: (563, 697)


In [138]:
image2.save('./Garbage/Image2.jpeg')

In [139]:
## https://www.geeksforgeeks.org/working-images-python/

# from PIL import Image 
  
# def main(): 
#     try: 
#         #Relative Path 
#         img = Image.open("picture.jpg")  
          
#         #Angle given 
#         img = img.rotate(180)  
          
#          #Saved in the same relative location 
#         img.save("rotated_picture.jpg") 
#     except IOError: 
#         pass
  
# if __name__ == "__main__": 
#     main()

In [140]:
import numpy as np
import time
import sys

boyut=100000

# Python List
lst1 = range(boyut)
lst2 = range(boyut)

# NumPy Array
arr1 = np.arange(boyut)
arr2 = np.arange(boyut)

start_time = time.time()
result1 = [(x+y) for x,y in zip(lst1, lst2) ]
print("Python liste için zamanı:", (time.time() - start_time )*1000, "ms ")

start_time  = time.time()
result2 = arr1 + arr2
print("Numpy dizi için zaman:", (time.time() - start_time )*100, "ms")

Python liste için zamanı: 10.970592498779297  ms 
Numpy dizi için zaman: 0.09987354278564453  ms


In [141]:
type(result1)

list

In [142]:
type(result2)

numpy.ndarray

In [143]:
result1 == result2

array([ True,  True,  True, ...,  True,  True,  True])